### ISSUE TITLE
The application asking for camera access in Chrome

### ISSUE THREAD

**Issue by prashen** [DevelopAppWithMe/whiteboard#1]
<img width="1440" alt="Screenshot 2022-05-10 at 3 12 32 PM" src="https://user-images.githubusercontent.com/5449548/167599801-25932033-6ead-41e4-b00a-4c3dfa548d32.png">
What is this man It's recording and taking microphone access with camera...

**Comment by devjayprakash** [comment]
There was a plan of implementing realtime audio and video calling in this whiteboard app and i had started working on that. That's the reason it's asking for camera and microphone access. Thje code for it is in the script.js file under public directory. Will start working on it soon.
